### ISSUE TITLE
docs: installpath for git is not correct anymore

### ISSUE THREAD

**Issue by rolfmertig** [wesley974/mailserver#15]
This
echo installpath=ftp2.fr.openbsd.org > /etc/pkg.conf
does not work anymore on OpenBSD 6.0.

This does work:
echo installpath=ftp.eu.openbsd.org > /etc/pkg.conf

**Comment by wesley974** [comment]
Ok thanks

**Comment by wesley974** [comment]
Do you want to use this old mailserver and try to upgrade ? Or are you interested in building a new mailserver ? You can write me.
