### ISSUE TITLE
Stable branch?

### ISSUE THREAD

**Issue by hkparker** [wesley974/mailserver#2]
Hello there!  I love to see an actively maintained OpenBSD mail server project, big fan of mailserv and glad I can run this on 5.9.  Before I set this up in production, I wanted to check if I should just be following the head of master, or if there is a better stable release?  Is `git pull` the best upgrade mechanism for future bugfixes?  Thanks!

**Comment by wesley974** [comment]
Hi,
You can run it of course in production. 
And let me know how it works :) 
If i add changes, it is minor.

**Comment by hkparker** [comment]
Great thanks, I'll be sure to share my results
