### ISSUE TITLE
Webmail path?

### ISSUE THREAD

**Issue by deksar** [wesley974/mailserver#4]
Does the installation modify any settings on Nginx and/or PHP module on the system? Let's assume that mailserver was installed into a Webserver box, would there be any conflicts?
While it reads as "To access Webmail, just browse https://ip_address" in README, I'd like to ask, what if there was an -already- actively running http server on https://ip_address (or http://ip_address)? 
Regular Webmail interface would be much better accessible on http://ip_address/webmail. How to achieve that?

**Comment by wesley974** [comment]
Mailserver has it own nginx.conf, php-fpm.conf, and modify php-5.6.ini.
By default webmail use : http(s)://IP
Admin panel : https://IP:4200

So, the best will be to install mailserver on a fresh OpenBSD install (as it said in README.md).
But i think you can tune easily nginx.conf to match what you need (for example running webmail on a different port, there are many solutions)
