### ISSUE TITLE
getting_started not found?

### ISSUE THREAD

**Issue by deksar** [wesley974/mailserver#5]
Started installing mailserver on an OpenBSD 5.9 VPS. Everything ran smooth till the step:
```
"Set the mailserver administrator
Just browse https://ip_address:4200/getting_started" 
```
When I browse that page with server's IP address, I get HTTP 404. 

/var/log/httpd.err reads as:

`2016/07/03 11:13:01 [error] 4022#0: *3 open() "/var/www/roundcubemail/getting_started" failed (2: No such file or directory), client: 88.200.xx.xx, server: $`

Tried rcctl restart nginx - no luck.
Any idea?
Thank you!

**Comment by deksar** [comment]
"server" block of the corresponding path in nginx.conf is as follows: 

` server {
    listen 4200;
    ssl on;
    root   /var/mailserver/admin/public;

    location ~* \.(ico|css|js|gif|jp?g|png) {
      access_log off;
      expires 7d;
      break;
    }

    location / {
      proxy_redirect   off;
      proxy_set_header Host              $host:4200;
      proxy_set_header X-Real-IP         $remote_addr;
      proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
      proxy_set_header X_Forwarded_Proto $scheme;

      if (!-f $request_filename.html) {
        proxy_pass  http://admin_mongrels;
      }
    }
  }
`

**Comment by wesley974** [comment]
Did you try from a fresh OpenBSD ??
Or from your existing Web server ?

2016-07-03 13:16 GMT+04:00 Özgür <notifications@github.com>:

**Comment by deksar** [comment]
A fresh OpenBSD installation plus just an nginx installation, default settings, nothing in use.

**Comment by wesley974** [comment]
Compare your existing /etc/nginx.conf with /var/mailserver/install/gui/nginx.conf (using diff -u)
Verify permission on nginx.conf (644)
Verify the flags for nginx (using cat /etc/rc.conf.local)

Debug using rcctl -d restart nginx

**Comment by wesley974** [comment]
Nginx need to be run with '-u', instead using chroot.

**Comment by deksar** [comment]
`# diff -u /etc/nginx/nginx.conf /var/mailserver/install/gui/nginx.conf
`
returns nothing. An exact copy? 

File perms. seems ok?
```
# ls -al /etc/nginx/nginx.conf
-rw-r--r--  1 root  wheel  3191 Jul  3 10:50 /etc/nginx/nginx.conf
```

and rc.conf.local file - it starts with -u: 
```
# cat /etc/rc.conf.local
nginx_flags=-u
ntpd_flags=-s
pkg_scripts=mysqld php56_fpm nginx spamassassin freshclam clamd clamav_milter dkimproxy_out postfix dovecot
smtpd_flags=NO
sndiod_flags=NO
spamassassin_flags=-s mail -u _spamdaemon -xq
```

Debugging nginx: 
```

# rcctl -d restart nginx
doing _rc_parse_conf
doing _rc_quirks
nginx_flags >-u<
doing _rc_read_runfile
doing _rc_parse_conf
doing _rc_quirks
nginx_flags >-u<
doing _rc_read_runfile
doing rc_check
nginx
doing rc_stop
doing _rc_wait stop
doing rc_check
doing rc_check
doing _rc_rm_runfile
(ok)
doing _rc_parse_conf
doing _rc_quirks
nginx_flags >-u<
doing _rc_read_runfile
doing rc_check
nginx
doing rc_start
doing _rc_wait start
doing rc_check
doing _rc_write_runfile
(ok)
```

**Comment by wesley974** [comment]
https://IP:4200/getting_started
=> This is in /var/mailserver/admin (main domain app), this has nothing to do with /var/www/roundcubemail

I think there's something wrong with your setup.

I'm going to try on a fresh install (following exactly all the steps), let you know.

**Comment by deksar** [comment]
I know it is weird. I'm trying to find a solution. 
nginx.conf server block for the port 4200 defines as follows (root path): 
```
 server {
    listen 4200;
    ssl on;
    root   /var/mailserver/admin/public;
```
However http error file states the error as:
`"/var/www/roundcubemail/getting_started" failed (2: No such file or directory)`

Strange.

**Comment by wesley974** [comment]
Could you check that : 
- https://IP 
Give the roundcube webmail
- Https://IP:4200 
Give the domain app

**Comment by wesley974** [comment]
Also check that you run the script : /var/mailserver/install/run_gui.sh
Verify that the app is running using : 
netstat -anf inet | grep LISTEN 
you need to see the ports : 

4213 & 4214 (domain app & account app)

**Comment by deksar** [comment]
https://ip : 502 Bad Gateway

httpd.err: 

`2016/07/03 12:05:06 [crit] 10732#0: *8 connect() to unix:/var/run/php-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 88.xx.xx., server: , request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "169.xx.xx."`

https://IP:4200: Mailserver Administration Page - it gave the admin page.

And NOW I tried again: https://IP:4200/getting_started,
it gave "Add System Administrator" Page! It seems it now runs, however I did nothing, weird. 

And https://ip still gives 502 Gateway err.

**Comment by deksar** [comment]
I definitely did run the run_gui.sh script. 

```
# netstat -anf inet | grep LISTEN
tcp          0      0  127.0.0.1.4214         *.*                    LISTEN
tcp          0      0  127.0.0.1.4213         *.*                    
```

**Comment by wesley974** [comment]
roundcubemail pkg is installed ?
Check that php-fpm pkg is installed and running...

What is your VPS ?? (mem/cpu/and disk )??

**Comment by wesley974** [comment]
you need minimum 512 MB RAM/CPU >1GHz DISK >=20GB

**Comment by deksar** [comment]
VPS: 2 vCores - 2.4 GHz - 8 GB RAM - 100 GB SSD. 

```
# ps auwx | grep php-fpm
root      8430  0.0  0.0 10004  2932 ??  Ss    12:38AM    0:07.77 php-fpm-5.6: master process (/etc/php-fpm.conf) (php-fpm-5.6)
www      18897  0.0  0.0 10028  2608 ??  I     12:38AM    0:00.01 php-fpm-5.6: pool www (php-fpm-5.6)
www      25842  0.0  0.0 10028  2652 ??  I     12:38AM    0:00.01 php-fpm-5.6: pool www (php-fpm-5.6)
root     30153  0.0  0.0   136   236 p0  R+    12:14PM    0:00.00 grep php-fpm
# pkg_info | grep php
php-5.6.18          server-side HTML-embedded scripting language
php-intl-5.6.18     intl library support for php5
php-mcrypt-5.6.18   mcrypt encryption/decryption extensions for php5
php-mysql-5.6.18    mysql database access extensions for php5
php-pdo_mysql-5.6.18 PDO mysql database access extensions for php5
php-pspell-5.6.18   pspell library extensions for php5
php-zip-5.6.18      zip functions for php5
```

**Comment by wesley974** [comment]
Could you restart php-fpm : 
/usr/sbin/rcctl restart php56_fpm

**Comment by deksar** [comment]
Restarting php56_fpm solved it. 
Thanks a lot for all your contribution and answers!

**Comment by wesley974** [comment]
Check also your php-fpm against the default : /var/mailserver/install/gui/php-fpm.conf

Your re welcome :)

& let me know how it works after fews days.
I'm still improve the shell scripting...

**Comment by deksar** [comment]
Sorry for re-opening this again. I just want to report every trouble I face, so mailserver could be much improved for everyone. 
After a reboot, https://IP:4200/ gives 502 Bad Gateway error. 
https://IP Roundcube webmail runs fine - I login to e-mail accounts as well, but the port 4200 doesn't work. 

Here are details: 

```
# cat /var/log/httpd.err
2016/07/03 12:59:51 [error] 5464#0: *29 connect() to 127.0.0.1:4213 failed (61: Connection refused) while connecting to upstream, client: 88.229.47.17, server: , request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:4213/", host: "164.132.231.49:4200"

```
And it seems 4213 & 4214 (domain app & account app) stopped listening after restart: 

```
# netstat -anf inet | grep LISTEN
tcp          0      0  127.0.0.1.3306         *.*                    LISTEN
tcp          0      0  127.0.0.1.8952         *.*                    LISTEN
tcp          0      0  *.4200                 *.*                    LISTEN
tcp          0      0  *.993                  *.*                    LISTEN
tcp          0      0  *.143                  *.*                    LISTEN
tcp          0      0  *.995                  *.*                    LISTEN
tcp          0      0  *.110                  *.*                    LISTEN
tcp          0      0  *.2000                 *.*                    LISTEN
tcp          0      0  *.4190                 *.*                    LISTEN
tcp          0      0  127.0.0.1.10028        *.*                    LISTEN
tcp          0      0  *.587                  *.*                    LISTEN
tcp          0      0  *.465                  *.*                    LISTEN
tcp          0      0  *.25                   *.*                    LISTEN
tcp          0      0  127.0.0.1.10027        *.*                    LISTEN
tcp          0      0  127.0.0.1.783          *.*                    LISTEN
tcp          0      0  *.443                  *.*                    LISTEN
tcp          0      0  *.80                   *.*                    LISTEN
```
Post Scriptum: php-fpm.conf was exact copy, as well.

**Comment by wesley974** [comment]
It is a normal behavior when you reboot the box, you can't access to the mail server admin.
I don't want it to be executed automatically on reboot (security).

If you want to change this behavior : 
echo /var/mailserver/install/run_gui.sh >> /etc/rc.local

Concerning your error (PHP message: PHP Warning: config.inc.php was not found) and the precedent error php-fpm, i think there are because your have firstly install packages/config files, they need to be merged.
