### ISSUE TITLE
Unlimited space mailbox?

### ISSUE THREAD

**Issue by deksar** [wesley974/mailserver#7]
Hello and thanks for recent updates, great effort! 
On the mailserver admin panel, how can I set unlimited space for an e-mail account? When we create an account, what should we write so it won't set any specific mailbox size limit for that account?
Thanks.

**Comment by wesley974** [comment]
Hi,

When you create a domain, you specify the "default quota" and the "max allowed quota".

Adding new account to this domain, you can let "quota" blank to set it to the default (you set ealier).
or set it to lower that earlier.
